### ISSUE TITLE
Cannot find module 'cordova-lib/src/cordova/platforms'

### ISSUE THREAD

**Issue by butchewing** [katzer/cordova-plugin-badge#29]
Cordova 5.0.0
`cordova plugin add de.appplant.cordova.plugin.badge`

```
Fetching plugin "de.appplant.cordova.plugin.badge" via cordova plugins registry
npm http GET http://registry.cordova.io/de.appplant.cordova.plugin.badge
npm http 304 http://registry.cordova.io/de.appplant.cordova.plugin.badge
Installing "de.appplant.cordova.plugin.badge" for ios
Failed to install 'de.appplant.cordova.plugin.badge':Error: Cannot find module 'cordova-lib/src/cordova/platforms'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Context.requireCordovaModule (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:48:12)
    at module.exports (/Users/butchewing/Projects/BYP/2015/app/plugins/de.appplant.cordova.plugin.badge/scripts/ios/didRegisterUserNotificationSettings.js:40:29)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:152:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:130:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
Error: Cannot find module 'cordova-lib/src/cordova/platforms'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Context.requireCordovaModule (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/Context.js:48:12)
    at module.exports (/Users/butchewing/Projects/BYP/2015/app/plugins/de.appplant.cordova.plugin.badge/scripts/ios/didRegisterUserNotificationSettings.js:40:29)
    at runScriptViaModuleLoader (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:152:18)
    at runScript (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:130:16)
    at /usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/hooks/HooksRunner.js:115:20
    at _fulfilled (/usr/local/lib/node_modules/cordova/node_modules/q/q.js:787:54)
```

**Comment by butchewing** [comment]
Updated everything. Removed Ionic Hooks. Issue is resolved.

**Comment by butchewing** [comment]
I was mistaken. The problem still exists. I think it must be as a result of Cordova v5.0.0

**Comment by ir-tech** [comment]
I have this bug as well... temporary fix was to remove the plugin.

**Comment by katzer** [comment]
Has been fixed with v.0.6.4
