### ISSUE TITLE
not compatible with the local notification plugin

### ISSUE THREAD

**Issue by nurfgun** [katzer/cordova-plugin-badge#40]
installing one without the other works perfectly but the two in presence of each other produce below:

```
** BUILD FAILED **


The following build commands failed:
	Ld build/emulator/demo.app/demo normal i386
(1 failure)
Error code 65 for command: xcodebuild with args: -xcconfig,/Users/daniel/demo/platforms/ios/cordova/build-debug.xcconfig,-project,demo.xcodeproj,ARCHS=i386,-target,demo,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/daniel/demo/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/daniel/demo/platforms/ios/build/sharedpch
ERROR building one of the platforms: Error: /Users/daniel/demo/platforms/ios/cordova/build: Command failed with exit code 2
You may not have the required environment or OS to build this project
Error: /Users/daniel/demo/platforms/ios/cordova/build: Command failed with exit code 2
    at ChildProcess.whenDone (/usr/local/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/superspawn.js:134:23)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
```

I was using the latest version of them with the latest version of ionic.

**Comment by nurfgun** [comment]
[same issue](https://github.com/katzer/cordova-plugin-local-notifications/issues/621)

**Comment by katzer** [comment]
Fixed
