### ISSUE TITLE
Error when trying to add the plugin

### ISSUE THREAD

**Issue by affinionmobile** [katzer/cordova-plugin-badge#48]
How can this be resolved?

```
Error happened [TypeError: Object.keys called on non-object]
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Object.getPluginFromFetchJsonByLocator (C:\Users\x\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\state.js:734:26)
    at Object.savePlugin (C:\Users\x\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\state.js:670:36)
    at C:\Users\x\AppData\Roaming\npm\node_modules\ionic\lib\ionic\cordova.js:90:22
    at _fulfilled (C:\Users\x\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\x\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\x\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:749:13)
    at C:\Users\x\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:557:44
    at flush (C:\Users\x\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:108:17)
    at process._tickCallback (node.js:355:11)
```

**Comment by katzer** [comment]
@affinionmobile Should be fixed with 0.7.2
